from datetime import datetime
import helics as h
import random
import logging
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation
from dots_infrastructure.CalculationServiceHelperFunctions import get_single_param_with_name
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem

# Imports generated by the DOTS code generator
from backupgen_service_base import BackupgenServiceBase
from backupgen_service_dataclasses import RealTimeBackupOutput

LOGGER = logging.getLogger(__name__)

class BackupgenService(BackupgenServiceBase):

    def init_calculation_service(self, energy_system: EnergySystem):
        super().init_calculation_service(energy_system)

    def real_time_backup(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        # Read the requested backup power command.
        requested_power_w = get_single_param_with_name(param_dict, "backup_requested_power")
        if requested_power_w is None:
            requested_power_w = 0.0

        # Generate a realistic actual output based on the requested power.
        # Backup gens typically supply 80-100% of requested power, with a bit of variability.
        actual_power_w = max(0.0, requested_power_w * random.uniform(0.8, 1.0) + random.uniform(-500, 500))

        # Generate the available maximum capacity around the dispatchable power.
        available_max_power = max(actual_power_w, requested_power_w, 10000.0) * random.uniform(1.0, 1.2)

        return RealTimeBackupOutput(
            backup_supplied_power=actual_power_w,
            available_max_power=available_max_power
        )

if __name__ == "__main__":
    helics_simulation_executor = BackupgenService()
    try:
        LOGGER.info("Starting simulation...")
        helics_simulation_executor.start_simulation()
    except Exception as e:
        LOGGER.error(f"Simulation crashed due to an error: {e}")
        # Raising the error is optional, but good for debugging so it doesn't fail silently
        raise 
    finally:
        LOGGER.info("Ensuring HELICS federate is finalized and simulation is stopped.")
        # This block executes NO MATTER WHAT, guaranteeing the broker is freed.
        helics_simulation_executor.stop_simulation()