from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem, GasProducer
from dots_infrastructure.EsdlHelperFunctions import EsdlHelperFunctions

# This file is generated, DO NOT edit this file!

class BackupgenServiceBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()
        self.esdl_obj_mapping : dict[EsdlId, GasProducer]= {}

        
        # Calculation: real_time_backup
        self.real_time_backup_period_seconds = 900
        real_time_backup_inputs = [
        
        ]
        real_time_backup_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="GasProducer",
                                    output_name="backup_supplied_power",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
            PublicationDescription(global_flag=True, 
                                    esdl_type="GasProducer",
                                    output_name="available_max_power",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
        ]
        real_time_backup_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="real_time_backup", 
            inputs=real_time_backup_inputs, 
            outputs=real_time_backup_outputs, 
            calculation_function=self.real_time_backup
        )
        self.add_calculation(real_time_backup_information)

    def init_calculation_service(self, energy_system: EnergySystem):
        all_esdl_objs = EsdlHelperFunctions.get_all_esdl_objects_from_type(energy_system.eAllContents(), GasProducer)
        for esdl_obj in all_esdl_objs:
            if hasattr(esdl_obj, "id"):
                self.esdl_obj_mapping[esdl_obj.id] = esdl_obj

    
    def real_time_backup(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    